CREATE TABLE quality
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pm25      DOUBLE PRECISION                        NOT NULL,
    pm10      DOUBLE PRECISION                        NOT NULL,
    no2       DOUBLE PRECISION                        NOT NULL,
    so2       DOUBLE PRECISION                        NOT NULL,
    o3        DOUBLE PRECISION                        NOT NULL,
    location  VARCHAR(255),
    timestamp TIMESTAMP WITH TIME ZONE,
    date      VARCHAR(255),
    latitude  DOUBLE PRECISION                        NOT NULL,
    longitude DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT "pk_qualıty" PRIMARY KEY (id)
);